#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# berry directory
DIR="$HOME/.config/berry"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/scripts/rofi_askpass

# execute the application
sudo -A $1
