#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# berry directory
DIR="$HOME/.config/berry"

# Launch dunst daemon
if [[ `pidof dunst` ]]; then
	pkill dunst
fi

dunst -config "$DIR"/dunstrc &
